### ISSUE TITLE
Couple issues with docker-compose setup

### ISSUE THREAD

**Issue by Cobertos** [sockethub/sockethub#511]
Just tried setting up with `docker-compose` and I ran into the following issues:

* No `version` in `docker-compose.yml` so I had to add one (giving me parsing errors)
* Changed `links` to `networks` (not sure if this was actually needed in the end)
* Had to change `Dockerfile` entrypoint and config copy path to different path because of `ADD . /app` and the current lerna-based repo design.
* Rearranged the Dockerfile so that it uses lerna now (so that it uses the local version of the platforms, otherwise it pulls from npm which is old and throws errors)
* Added `depends_on` to wait for redis to start

Here's the final files

docker-compose.yml
```yml
version: "3.6"
services:
  sockethub:
    build: .
    ports:
      - "10550:10550"
    networks:
      - sockethub-net
    depends_on:
      - redis
  redis:
    image: redis
    networks:
      - sockethub-net

networks:
  sockethub-net:

```

Dockerfile
```Dockerfile
FROM node:16
MAINTAINER Ben Kero <ben.kero@gmail.com>

RUN mkdir -p /app
WORKDIR /app
ADD . /app

RUN npm install
RUN npx lerna bootstrap
RUN npx lerna run build

ADD packages/sockethub/config.json.example /app/packages/sockethub/config.json

EXPOSE 10550
CMD DEBUG=sockethub* /app/packages/sockethub/bin/sockethub --examples --host 0.0.0.0

```

I'll loop back and make a PR if these changes seem sane to the maintainers
